### ISSUE TITLE
disk image is 20Gig

### ISSUE THREAD

**Issue by Gys** [nlf/dlite#73] opened 2016-01-31 14:21 UTC
I saw the remark that sparse disks are not supported yet. However, I did not expect dlite to create a 20Gig disk in some hidden folder... 

The blog says: 'Currently the operating system in use is DhyveOS another of my projects that was created with the intention of giving you the smallest possible OS to allow running Docker'. The smallest possible OS needs a 20Gig disk ? We have a different opinion on small I think ;-)

I also read the (closed) issue that this is the same as docker-machine uses (before it was even more ?!). However for docker-machine that is the max, it will start much (much) smaller. At the very least I think you should add this min/max size explicitly to the readme. And actually I think it should be much less. As also stated in the readme this is for test and dev purposes only. If anyone really needs such a huge disk then they better use separate (virtual) volume for that ?!

**Comment by kitten** [comment] 2016-01-31 15:47
This is basically a duplicate of #55 (-ish?). That issue was answered that sparse disk support is not wanted and raw disk support is the actual goal for the time coming.

However you seem to have the misconception that dhyve-os is responsible for the disk size, which it is not. Most of the disk is going to be empty after dlite allocates the disk space for it. This has nothing to do with dhyve-os.

You can even make a smaller disk by passing a `-d` option to the `dlite install` command.

**Comment by Gys** [comment] 2016-01-31 16:09
'Most of the disk is going to be empty after dlite allocates the disk space for it. This has nothing to do with dhyve-os.'

Sorry, bad joke. I was aware of that. But the 'most of the disk is going to be empty' is exactly the season why I think it should be smaller. 

I was not aware of the `-d` option. Its not shown in `dlite -h`. It also works with `rebuild` I noticed and takes a number as argument (= Gb).

What is the reason for occupying so much space on my physical disk by default ? Especially because its possible to easily do a rebuild with a bigger size if needed.

**Comment by kitten** [comment] 2016-01-31 16:40
A rebuild will destroy all your data in the VM, so I guess that's inconvenient. Also 20Gigs shouldn't be too much. We could even choose another size. But the reason it's that big is just that docker machines chooses the same size.

Overall you shouldn't be using dlite if the current shortcomings are that critical to your workflow, as with similar projects ;)

It's probably a good idea to keep an issue opened for raw dis support, @nlf?

**Comment by nlf** [comment] 2016-02-01 18:02
yes it is. and until the sparse disk support is in place it will stay there. pulling docker images can take up quite a bit of room a lot faster than you'd think.

i will open a new tracking issue for sparse images though

**Closed as completed by nlf** 2016-02-01 18:02 UTC
