### ISSUE TITLE
Launchd script not working (OSX 10.11.3)

### ISSUE THREAD

**Issue by maltefiala** [nlf/dlite#16] opened 2016-01-21 08:46 UTC
Unfortunately, the launchd script is not working on OSX 10.11.3. Exit code 78. (Running `sudo dlite daemon` is working fine.)

``` bash
-   78  local.dlite
```

Last line in sudoers seems fine:

``` bash
<username> ALL=(ALL) NOPASSWD: /usr/local/bin/dlite
```

No output even after adding log redirection:

``` bash
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
        <dict>
                <key>Label</key>
                        <string>local.dlite</string>
                <key>ProgramArguments</key>
                        <array>
                                <string>/usr/bin/sudo</string>
                                <string>/usr/local/bin/dlite</string>
                                <string>daemon</string>
                        </array>
                <key>StandardOutPath</key>
                        <string>/var/log/dlite.log</string>
                <key>StandardErrorPath</key>
                        <string>/var/log/dlite.err</string>
                <key>Debug</key>
                        <true/>
        </dict>
</plist>
```

**Comment by maltefiala** [comment] 2016-01-21 12:48
Launchd in OSX 10.11 has seen a large overhaul. Unfortunately, I was not able to fix the plist file. However, here are some findings:

``` bash
                <key>Debug</key>
                        <true/>
```

.. is no longer allowed

`15D21` is the OSX build (seems trivial but necessary to mention as it appears in launchd output).

Btw, my permissions seem fine:

``` bash
-rw-r--r--   1 <username>  staff   584 Jan 21 12:29 local.dlite.plist
```

**Comment by maltefiala** [comment] 2016-01-21 12:53
After doing everything by hand it is working. I have to admit I have no idea why. Following steps fixed the problem for me:

``` bash
launchctl remove local.dlite
vi ~/Library/LaunchAgents/local.dlite.plist
```

Insert:

``` bash
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
          <key>Label</key>
                <string>local.dlite</string>
                <key>ProgramArguments</key>
                <array>
                  <string>/usr/bin/sudo</string>
                  <string><PATH TO EXECUTABLE></string>
                        <string>daemon</string>
                </array>
                <key>RunAtLoad</key>
                <true/>
  </dict>
</plist>
```

``` bash
launchctl load local.dlite.plist
```

**Comment by nlf** [comment] 2016-01-21 21:38
I'm confused.. so after an installation the agent didn't work, but after you deleted the contents of the file and recreated it yourself, it did work?

**Comment by maltefiala** [comment] 2016-01-21 23:05
Correct. I will re-evaluate over the weekend. Please ignore.

**Comment by ruimarinho** [comment] 2016-01-25 19:59
On a fresh install, I was also unable to run the plist on the first run.

Manually executing `sudo /usr/local/bin/dlite daemon` turned out this:

```
Reloading nfds failed: exit status 1
nfsd: nfsd not running?
```

Execute `sudo nfsd start` outputted:

```
sudo nfsd start
The nfsd service is already running.
```

I attempted to do `launchctl load ~/Library/LaunchAgents/local.dlite.plist` before trying `launchctl start local.dlite` again, so the load command is likely unnecessary. In any case, it not works correctly without requiring any modification to the original plist.

**Comment by nlf** [comment] 2016-01-25 20:07
oh interesting, so maybe the nfsd restart is what's failing and the plist issue is a red herring

**Comment by ruimarinho** [comment] 2016-01-25 20:15
Yep, I'll see if I can test on a fresh install later to make sure that the plist load does not in fact have anything to do with the failure of start.

In any case, I'm not sure why nfsd fails to be reloaded by dlite..

**Comment by sscarduzio** [comment] 2016-01-25 21:04
+1 identical case, is there a workaround?

**Comment by nlf** [comment] 2016-01-25 21:05
you might try starting nfsd _before_ installing (i.e. `touch /etc/exports && sudo nfsd start`) but i'm not sure if it will want an actual export in the file before it'll start or not

**Comment by seven1m** [comment] 2016-01-25 21:10
This fixed it for me:

```
sudo chown timmorgan:staff /Users/timmorgan/Library/LaunchAgents/local.dlite.plist
launchctl start local.dlite
```

**Comment by sfermigier** [comment] 2016-01-25 21:20
Under Mac OS 10.10.5, I had to do a chown on the `local.dlite.plist` as @seven1m did.

Also I had to clean my `/etc/exports` from a few entries that were, seemingly, added by Vagrant.

**Comment by nlf** [comment] 2016-01-25 21:21
i just released a new version, 1.0.4, that will make sure that the launchd plist is owned by the correct user

**Comment by seven1m** [comment] 2016-01-25 21:37
Thanks @nlf!

**Comment by maltefiala** [comment] 2016-01-25 22:04
Regarding chown, see Apple reference:

> Daemons and agents that are installed globally must be owned by the root user. Agents installed for the current user must be owned by that user. All daemons and agents must not be group writable or world writable. (That is, they must have file mode set to 600 or 400.)

https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-104738

**Comment by CedricGatay** [comment] 2016-01-25 22:29
@nlf it only worked after I did a `launchctl load ~/Library/LaunchAgents/local.dlite.plist` and then the next `launchctl start local.dlite` worked.
Hats off for the tool ;)

**Comment by nlf** [comment] 2016-01-25 22:31
doh, that's a documentation error more than anything. i'll fix that

**Comment by ruimarinho** [comment] 2016-01-25 22:35
@CedricGatay so I think your comment proves that the load is necessary after all. Btw, doesn't a user-space agent requiring sudo fit the case for a LaunchDaemon?

**Comment by nlf** [comment] 2016-01-25 22:37
the issue is that launch daemons run as root, and not as your user. since i'm storing all the related files in a user's home directory, and presumably different users on the same computer may want their own virtual machine, i wanted the service to run as the user. the choice to use an agent instead of a daemon was intentional :)

**Comment by CedricGatay** [comment] 2016-01-25 22:40
I like this approach more than a system wide setup. Easy to setup, easy to use, the right tool for the right job !

**Comment by ruimarinho** [comment] 2016-01-25 22:40
Makes sense - it does require some boilerplate (e.g. chowning, sudoers), but it looks like it is becoming a solid process as most of that logic is moved to the project installer. :+1:

**Comment by nlf** [comment] 2016-01-26 00:03
i think i'm going to declare this issue resolved and close it. if there are more problems, we can always reopen or open new issues. thanks everyone for your help in debugging this and your feedback, it was incredibly valuable!

**Closed as completed by nlf** 2016-01-26 00:03 UTC
Labels: bug
