### ISSUE TITLE
Having trouble getting it started

### ISSUE THREAD

**Issue by mattbailey** [nlf/dlite#27] opened 2016-01-26 04:55 UTC
after install:

```
$ launchctl start local.dlite
Not privileged to start service.
```

OK, I guess I'll just try to start it manually...

```
$ sudo dlite daemon
COM1 connected to /dev/ttys005
rdmsr to register 0x570 on vcpu 0
rdmsr to register 0x570 on vcpu 1
rdmsr to register 0x34 on vcpu 0
```

I guess that means it's running, but `docker ps` in another terminal just hangs

**Comment by djui** [comment] 2016-01-26 10:01
`launchctl start local.dlite` should work (as described and I can reproduce it). To me it hints at your environment deviated from other users. Can you list permissions on the launch file (`ls l-h $HOME/Library/LaunchAgents/local.dlite.plist`) and all other dlite files (`ls -lh ~/.dlite`)?

**Comment by robholland** [comment] 2016-01-26 10:25
docker ps hangs for me also.

Maybe related, I can't ssh with as user docker with the password docker as per dhyve-os README. There is an SSH server there though, so something is running...

```
$ ssh docker@local.docker
docker@local.docker's password:
Permission denied, please try again.
```

```
$ ls -l Library/LaunchAgents/
...
-rw-r--r--  1 robholland  staff  431 26 Jan 10:14 local.dlite.plist
-rw-r--r--@ 1 robholland  staff  677 30 Nov 15:38 org.virtualbox.vboxwebsrv.plist
...
```

```
$ ls -l ~/.dlite/
total 62938200
-rw-r--r--  1 robholland  staff      3219840 26 Jan 10:14 bzImage
-rw-r--r--  1 robholland  staff           72 26 Jan 10:14 config.json
-rw-r--r--  1 robholland  staff  32212254720 26 Jan 10:18 disk.img
-rw-r--r--  1 robholland  staff      8876008 26 Jan 10:14 rootfs.cpio.xz
```

**Comment by djui** [comment] 2016-01-26 10:29
Could it be that your default SSH key has a passphrase and dlite can't handle the input for that?

**Comment by robholland** [comment] 2016-01-26 10:33
That's not the case for me:

```
$ cd ~/.ssh
$ ssh localhost
Password:
$ cp id_rsa.pub authorized_keys
$ ssh localhost
Last login: Tue Jan 26 10:32:02 2016 from localhost
```

**Comment by robholland** [comment] 2016-01-26 10:35
Ok, I uninstalled dlite and installed it again and now it's working. When I installed previously I had run VirtualBox since booting, maybe that's somehow related. Let me know anything else it might be useful for you to know, although I can't really debug the issue now.

**Comment by swissmanu** [comment] 2016-01-26 10:44
I had the same problem, `docker ps` hung after setting up `dlite`.
When installing the first time, I used a specific SSH keypair using the `-s` parameter. I did not use a specific one when doing the reinstall, et voilà: Everything works.

**Comment by djui** [comment] 2016-01-26 10:47
@swissmanu I think the SSH myth might be busted. I set my money on an outdated `/etc/hosts` `local.docker` entry.

I also had the problem of docker hanging now myself, ironically, after uninstall and reinstalling it (to reduce the disk space used from 30GiB to 20GiB).

When looking at `/etc/hosts` I could see that
1. Even after uninstall dlite, the `local.docker` entry was present.
2. After removing the entry manually and then reinstalling dlite, no entry was added until starting `launchctl load ...`.

So my hypothesis is: After removing, the hosts entry is not removed. The when reinstalling and starting, dlite's daemon (or the agent) finds an entry already, assumes that's the correct one, but in the meantime the IP has changed and therefore hangs.

Could you verify this?

**Comment by nlf** [comment] 2016-01-26 17:21
great info here, i'll do some tweaking to make sure the hosts entry is cleaned up properly on uninstall.

also note that if you can't ssh to the vm as the `docker` user, try using the `root` user with password `dhyve`

**Comment by mattbailey** [comment] 2016-01-26 17:57
so the `~/.dlite` directory and everything under it are owned by my user, 755 for the dir 644 for the files.

if I run it manually with `sudo dlite daemon` I can ping local.docker, and ssh into it.  I _did_ use a custom ssh key when I did init, and I can ssh successfully to it with that key.  I'll try again with a "default" ssh key.

**Comment by mattbailey** [comment] 2016-01-26 18:01
Rebuilding now, but I have a suspicion this is due to the sudoers entry that dlite injects does not cover granting access to my ~/.ssh/*.pub files, of which, my custom made ones are ALL chmod'd 600.

update: welp that didn't help, still getting:

```
launchctl start local.dlite
Not privileged to start service.
```

However, starting the daemon manually, allows docker to function from the host:

```
my host$ docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-dhyve
Operating System: Buildroot 2015.11.1
CPUs: 1
Total Memory: 997.3 MiB
Name: dlite
ID: HW5L:EOKR:NQ73:O5VH:DKZ4:MOOB:3JC3:F7Q2:WGPQ:PVGT:6NAO:UL4Y
```

update again:
Oops, launchctl does not work properly from within `tmux`, so might want to make a note that in the documentation. So, that issue is fixed.  Testing to see if the SSH issue independent.

**Comment by mattbailey** [comment] 2016-01-26 18:16
It appears to work fine now, but a couple things to note:

`sudo dlite uninstall` did not appear to unload or stop the launchctl plist

And, I'm still not sure what caused docker from the host to just hang.

**Comment by swissmanu** [comment] 2016-01-27 07:09
@djui just tried to reconstruct the situation and it seems you were right about the `/etc/hosts` entry.
thanks for your time :)

**Comment by djui** [comment] 2016-01-27 14:07
I get the feeling not running `launchctl unload ~/Library/LaunchAgents/local.dlite.plist` and/or launchctl stop local.dlite`does also affect the problem. I guess`uninstall`needs to make sure`unload`+`stop`+sed on etc/hosts is run.

**Comment by jstop** [comment] 2016-01-27 14:24
Not sure if this is related, but I had similar problems initially because launchctl commands have problems if run inside tmux

**Comment by nlf** [comment] 2016-01-27 17:26
added notes to the troubleshooting section about tmux and also conflicting hosts file entries. i also already patched the uninstall command to stop and unload the agent before removing files. i'm going to close this issue, but do reopen it if you still have problems after the update (which i'll release later today)

**Closed as completed by nlf** 2016-01-27 17:26 UTC
Labels: bug

**Comment by mattbailey** [comment] 2016-01-27 18:00
@nlf I also noticed after uninstall/install I had 2 entries in `/etc/sudoers`
