### ISSUE TITLE
Forwarding ports?

### ISSUE THREAD

**Issue by synic** [nlf/dlite#163] opened 2016-04-07 15:48 UTC
Is there a way to expose a port on the VM to the mac?  

I'd like to type `telnet localhost 8000` and have it forward to 8000 in the VM itself.

**Comment by nlf** [comment] 2016-04-07 15:58
there is, but it's just a matter of setting up your mac's firewall to do it for you. [this link](https://gist.github.com/kujohn/7209628) has some great information on how to do it, you'll just have to change the target IP to be that of your VM.

alternatively you could use an ssh tunnel to serve the same purpose, something like `ssh -L 8000:local.docker:8000 -N docker@local.docker` should do the trick, though it will only work so long as that ssh client is running.

**Comment by synic** [comment] 2016-04-07 16:09
I actually tried something similar to that, but with no luck:

http://superuser.com/questions/1062213/trouble-forwarding-a-port-on-os-x-with-pf

**Comment by nlf** [comment] 2016-04-07 16:32
this isn't actually something i personally even do, so i have limited experience/knowledge here. if the issue is with pfctl then i'm afraid i can't really help. it's _possible_ that the issue is the vm being on a different interface, so you might try checking out this part of those instructions: https://gist.github.com/kujohn/7209628#5-forwarding-across-interfaces

**Comment by nlf** [comment] 2016-04-24 01:36
closing this since it's more or less unrelated to dlite and is a general networking question

**Closed as completed by nlf** 2016-04-24 01:36 UTC
Labels: question
